-- Crear secuencias
CREATE SEQUENCE IF NOT EXISTS usuario_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS companiero_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS adopcion_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS extravio_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS postulacion_id_seq START WITH 1 INCREMENT BY 1;

-- Crear tabla usuario
CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT DEFAULT nextval('usuario_id_seq') PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    celular INTEGER,
    email VARCHAR(255),
    direccion VARCHAR(255),
    administrador BOOLEAN
);

-- Crear tabla companiero (mascota)
CREATE TABLE IF NOT EXISTS companiero (
    id BIGINT DEFAULT nextval('companiero_id_seq') PRIMARY KEY,
    nombre VARCHAR(255),
    especie VARCHAR(255),
    raza VARCHAR(255),
    sexo CHAR(1),
    color VARCHAR(255),
    descripicon VARCHAR(255),
    f_naciemiento DATE,
    esterilizado BOOLEAN,
    chipeado BOOLEAN,
    tamanio VARCHAR(255),
    familiar BIGINT REFERENCES usuario(id)
);

-- Crear tabla adopcion
CREATE TABLE IF NOT EXISTS adopcion (
    id BIGINT DEFAULT nextval('adopcion_id_seq') PRIMARY KEY,
    administrador BIGINT REFERENCES usuario(id),
    mascota BIGINT REFERENCES companiero(id),
    requisitos VARCHAR(255) NOT NULL,
    transito BOOLEAN NOT NULL
);

-- Crear tabla extravio
CREATE TABLE IF NOT EXISTS extravio (
    id BIGINT DEFAULT nextval('extravio_id_seq') PRIMARY KEY,
    creador BIGINT,
    mascota BIGINT,
    zona VARCHAR(255),
    hora TIMESTAMP,
    tiempo_gracia TIMESTAMP, 
    observacion VARCHAR(255)
);

ALTER TABLE public.extravio ADD ultimo_avistamiento timestamp NOT null default NOW();

-- Crear tabla postulacion
CREATE TABLE IF NOT EXISTS postulacion (
    id BIGINT DEFAULT nextval('postulacion_id_seq') PRIMARY KEY,
    usuario BIGINT REFERENCES usuario(id),
    adopcion BIGINT REFERENCES adopcion(id),
    fecha DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS  avistamiento (
         id BIGINT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
         comentario varchar(255) NULL,
         extravio  BIGINT REFERENCES extravio(id),
         hora timestamp NULL,
         usuario BIGINT NULL,
         zona varchar(255) NULL,
         latitud float8 NULL,
         longitud float8 NULL,
         CONSTRAINT avistamiento_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS  emergencia(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    creador BIGINT NOT NULL REFERENCES usuario(id),
    zona VARCHAR(255)  NULL,
    latitud float8 NULL,
    longitud float8 NULL,
    hora TIMESTAMP  NOT NULL DEFAULT NOW(),
    observacion varchar(255) NULL,
    atendido BOOLEAN NOT NULL DEFAULT FALSE
    CONSTRAINT emergencia_pkey PRIMARY KEY (id)
)


CREATE TABLE IF NOT EXISTS  extraviofav(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    usuario BIGINT NOT NULL REFERENCES usuario(id),
    extravio BIGINT NOT NULL REFERENCES extravio(id),
    CONSTRAINT extraviofav_pkey PRIMARY KEY (id),
    CONSTRAINT sk_usuario_extravio UNIQUE (usuario, extravio)
)