-- ==========================================
-- 1. CREACIÓN DE SECUENCIAS
-- ==========================================

--- ESTE SCRIPT ESTA EN LA BASE DE DATOS DEL SERVICIO DE RAILWAY

CREATE SEQUENCE IF NOT EXISTS usuario_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS companiero_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS adopcion_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS extravio_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS postulacion_id_seq START WITH 1 INCREMENT BY 1;

-- ==========================================
-- 2. CREACIÓN DE TABLAS PRINCIPALES
-- ==========================================

-- Tabla Usuario
-- Incluye campos originales + campos de Firebase/Push del script 4
CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT DEFAULT nextval('usuario_id_seq') PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    celular INTEGER,
    email VARCHAR(255),
    direccion VARCHAR(255),
    administrador BOOLEAN,
    firebase_uid VARCHAR(255) UNIQUE,
    push_token TEXT,
    notificaciones_habilitadas BOOLEAN DEFAULT true
);

-- Tabla Compañero (Mascota)
-- Se han eliminado los NOT NULL según el script 3 y modificado 'familiar' según script 2
CREATE TABLE IF NOT EXISTS companiero (
    id BIGINT DEFAULT nextval('companiero_id_seq') PRIMARY KEY,
    nombre VARCHAR(255),
    especie VARCHAR(255),
    raza VARCHAR(255),
    sexo CHAR(1),
    color VARCHAR(255),
    descripicon VARCHAR(255),
    f_naciemiento DATE,
    esterilizado BOOLEAN,
    chipeado BOOLEAN,
    tamanio VARCHAR(255),
    familiar BIGINT REFERENCES usuario(id) -- Es nullable por defecto al no poner NOT NULL
);

-- Tabla Adopción
CREATE TABLE IF NOT EXISTS adopcion (
    id BIGINT DEFAULT nextval('adopcion_id_seq') PRIMARY KEY,
    administrador BIGINT REFERENCES usuario(id),
    mascota BIGINT REFERENCES companiero(id),
    requisitos VARCHAR(255) NOT NULL,
    transito BOOLEAN NOT NULL
);

-- Tabla Extravío
-- Consolida campos del script 1 y script 2 (geo, resuelto, defaults)
CREATE TABLE IF NOT EXISTS extravio (
    id BIGINT DEFAULT nextval('extravio_id_seq') PRIMARY KEY,
    creador BIGINT,
    mascota BIGINT,
    zona VARCHAR(255),
    hora TIMESTAMP,
    tiempo_gracia TIMESTAMP, 
    observacion VARCHAR(255),
    ultimo_avistamiento TIMESTAMP NOT NULL DEFAULT NOW(),
    resuelto BOOLEAN DEFAULT FALSE,
    latitud DOUBLE PRECISION,
    longitud DOUBLE PRECISION,
    direccion VARCHAR(500),
    creado_By_Familiar BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabla Postulación
CREATE TABLE IF NOT EXISTS postulacion (
    id BIGINT DEFAULT nextval('postulacion_id_seq') PRIMARY KEY,
    usuario BIGINT REFERENCES usuario(id),
    adopcion BIGINT REFERENCES adopcion(id),
    fecha DATE NOT NULL
);

-- Tabla Avistamiento
-- Consolida script 1 y campos geo del script 2
CREATE TABLE IF NOT EXISTS avistamiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    comentario VARCHAR(255) NULL,
    extravio BIGINT REFERENCES extravio(id),
    hora TIMESTAMP NULL,
    usuario BIGINT NULL,
    zona VARCHAR(255) NULL,
    latitud DOUBLE PRECISION NULL,
    longitud DOUBLE PRECISION NULL,
    CONSTRAINT avistamiento_pkey PRIMARY KEY (id)
);

-- Tabla Emergencia
-- Consolida script 1 y agrega la FK mascota del script 2
CREATE TABLE IF NOT EXISTS emergencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    creador BIGINT NOT NULL REFERENCES usuario(id),
    zona VARCHAR(255) NULL,
    latitud DOUBLE PRECISION NULL,
    longitud DOUBLE PRECISION NULL,
    hora TIMESTAMP NOT NULL DEFAULT NOW(),
    observacion VARCHAR(255) NULL,
    atendido BOOLEAN NOT NULL DEFAULT FALSE,
    mascota BIGINT NOT NULL DEFAULT 1 REFERENCES companiero(id),
    CONSTRAINT emergencia_pkey PRIMARY KEY (id)
);

-- Tabla ExtravioFav
CREATE TABLE IF NOT EXISTS extraviofav (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    usuario BIGINT NOT NULL REFERENCES usuario(id),
    extravio BIGINT NOT NULL REFERENCES extravio(id),
    CONSTRAINT extraviofav_pkey PRIMARY KEY (id),
    CONSTRAINT sk_usuario_extravio UNIQUE (usuario, extravio)
);

-- ==========================================
-- 3. GESTIÓN DE IMÁGENES (SCRIPT 5)
-- ==========================================

-- Tabla principal de imágenes
CREATE TABLE IF NOT EXISTS imagen (
    id BIGSERIAL PRIMARY KEY,
    nombre_archivo VARCHAR(255) NOT NULL,
    ruta_storage VARCHAR(500) NOT NULL,
    url_publica VARCHAR(1000),
    tipo_mime VARCHAR(100),
    tamanio BIGINT,
    fecha_subida TIMESTAMP DEFAULT NOW()
);

-- Tabla intermedia: Mascotas e Imágenes
CREATE TABLE IF NOT EXISTS mascota_imagen (
    mascota_id BIGINT NOT NULL,
    imagen_id BIGINT NOT NULL,
    orden INT DEFAULT 0,
    PRIMARY KEY (mascota_id, imagen_id),
    CONSTRAINT fk_mascota FOREIGN KEY (mascota_id) 
        REFERENCES companiero(id) ON DELETE CASCADE,
    CONSTRAINT fk_mascota_imagen FOREIGN KEY (imagen_id) 
        REFERENCES imagen(id) ON DELETE CASCADE
);

-- Tabla intermedia: Extravíos e Imágenes
CREATE TABLE IF NOT EXISTS extravio_imagen (
    extravio_id BIGINT NOT NULL,
    imagen_id BIGINT NOT NULL,
    orden INT DEFAULT 0,
    PRIMARY KEY (extravio_id, imagen_id),
    CONSTRAINT fk_extravio FOREIGN KEY (extravio_id) 
        REFERENCES extravio(id) ON DELETE CASCADE,
    CONSTRAINT fk_extravio_imagen FOREIGN KEY (imagen_id) 
        REFERENCES imagen(id) ON DELETE CASCADE
);

-- Tabla intermedia: Avistamientos e Imágenes
CREATE TABLE IF NOT EXISTS avistamiento_imagen (
    avistamiento_id BIGINT NOT NULL,
    imagen_id BIGINT NOT NULL,
    orden INT DEFAULT 0,
    PRIMARY KEY (avistamiento_id, imagen_id),
    CONSTRAINT fk_avistamiento FOREIGN KEY (avistamiento_id) 
        REFERENCES avistamiento(id) ON DELETE CASCADE,
    CONSTRAINT fk_avistamiento_imagen FOREIGN KEY (imagen_id) 
        REFERENCES imagen(id) ON DELETE CASCADE
);

-- Tabla intermedia: Adopciones e Imágenes
CREATE TABLE IF NOT EXISTS adopcion_imagen (
    adopcion_id BIGINT NOT NULL,
    imagen_id BIGINT NOT NULL,
    orden INT DEFAULT 0,
    PRIMARY KEY (adopcion_id, imagen_id),
    CONSTRAINT fk_adopcion FOREIGN KEY (adopcion_id) 
        REFERENCES adopcion(id) ON DELETE CASCADE,
    CONSTRAINT fk_adopcion_imagen FOREIGN KEY (imagen_id) 
        REFERENCES imagen(id) ON DELETE CASCADE
);

-- ==========================================
-- 4. ÍNDICES
-- ==========================================

-- Índices de Geolocalización
CREATE INDEX IF NOT EXISTS idx_extravio_location ON extravio (latitud, longitud);
CREATE INDEX IF NOT EXISTS idx_avistamiento_location ON avistamiento (latitud, longitud);

-- Índices de Firebase
CREATE INDEX IF NOT EXISTS idx_usuario_firebase_uid ON usuario(firebase_uid);

-- Índices de Imágenes
CREATE INDEX IF NOT EXISTS idx_mascota_imagen_mascota ON mascota_imagen(mascota_id);
CREATE INDEX IF NOT EXISTS idx_extravio_imagen_extravio ON extravio_imagen(extravio_id);
CREATE INDEX IF NOT EXISTS idx_avistamiento_imagen_avistamiento ON avistamiento_imagen(avistamiento_id);
CREATE INDEX IF NOT EXISTS idx_adopcion_imagen_adopcion ON adopcion_imagen(adopcion_id);
CREATE INDEX IF NOT EXISTS idx_imagen_fecha ON imagen(fecha_subida);
